---
title: "Alexander H. von Hafften - Research"
subtitle: "Ph.D. Candidate in Economics and Finance at UW-Madison"
---

:::: {style="display: grid; grid-template-columns: 1fr 5fr; grid-column-gap: 10px;"}

::: {}

```{r child ='sidebar_nav.Rmd'}
```

:::

::: {}

#### Working Papers


[Secondary-Market Capital Prices and Financial Frictions in Real Business Cycles](https://github.com/vonhafften/vonhafften.github.io/blob/main/research/jmp/paper.pdf) (Job Market Paper)

Secondary market capital prices are procyclical and volatile. This paper quantifies the role of financial frictions in amplifying secondary market capital price changes in response to aggregate productivity and credit shocks. To do so, I develop a quantitative industry equilibrium model of investment and capital reallocation with heterogeneous firms, endogenous entry and exit, and heterogeneous capital durability. I calibrate the model to match key moments in the dynamics of the universe of U.S. firms. Financially constrained firms are net buyers of less durable capital because of its lower upfront cost despite its lower future resale value. Financially constrained firms are more responsive to aggregate productivity and credit shocks than less financially constrained firms, so financial frictions amplify movements in secondary market capital prices. I decompose secondary market capital price volatility into 90 percent fundamental volatility and 10 percent amplification from financial frictions. When secondary market capital prices are held fixed, aggregate output volatility is 111 percent  of the baseline. Allowing secondary market capital prices to follow frictionless dynamics attenuates output volatility by 8 percent and the remaining 3 percent stems from the amplified secondary market capital prices from financial frictions.

[The Consequences of Missing the Trees for the Forest](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4665157) - August 2025 - with [Michael B. Nattinger](https://www.michaelnattinger.com) -  [Paper](https://github.com/vonhafften/vonhafften.github.io/blob/main/research/het_firm_carbon_tax/paper.pdf)

We document that the heterogeneity of carbon emission intensity across U.S. public firms is substantial and persistent. Using a tractable heterogeneous-firm GE model, we show that heterogeneity in carbon dependence is quantitatively relevant for determining the socially optimal carbon tax. With heterogeneity in this dimension and endogenous entry and exit, the firm distribution becomes endogenously greener in terms of production technology in response to carbon taxes - a composition effect which is absent from models without this heterogeneity. Omitting this channel, the model-implied Pigouvian tax which implements the socially optimal allocation is 86 percent higher than when the composition effect is present, suggesting that integrated assessment models abstracting from this form of heterogeneity may recommend carbon taxes that are larger than optimal. Nevertheless, we find that the welfare consequences of implementing the too-large carbon taxes are much smaller than the consequences of ignoring climate change altogether.

#### Publications Before Graduate School

[Are Incurred Loss Standards Countercyclical? A Case Study Using U.S. Bank Holding Company Data](https://www.mdpi.com/1911-8074/15/3/111) - February 2022

Journal of Risk and Financial Management Vol. 15 (3) with Fang Du and Diana Hancock

[The Costs and Benefits of Bank Capital – A Review of the Literature](https://www.mdpi.com/1911-8074/13/4/74)	- April 2020

Journal of Risk and Financial Management Vol. 13 (74) with Oliver de Bandt, Diana Hancock, Matías Gutiérrez Girault, Valerio Scalone, Hitoshi Mio, Tord Krogh, Michael Straghan, Arzu Uluc, Simon Firestone, Missaka Warusawitharana, Don Morgan, and Ajay Palvia

[Financing Affordable and Sustainable Homeownership with Fixed-COFI Mortgages](https://doi.org/10.1016/j.regsciurbeco.2018.08.002) - January 2020

Regional Science and Urban Economics Vol. 80 with Wayne Passmore

- Presented at the American Real Estate and Urban Economics Association 2018 National Conference

[Assessing Major Country Exposures of U.S. Banks Using 009a Data Reports: A Brexit Case Study](https://doi.org/10.17016/2380-7172.2469)	- November 2019

Finance and Economics Discussion Series Notes

[Are Basel's Capital Surcharges for Global Systemically Important Banks Too Small?](https://www.ijcb.org/journal/ijcb19q1a3.htm) - March 2019 

International Journal of Central Banking with Wayne Passmore

[Survey on the interaction of regulatory instruments: results and analysis](https://www.bis.org/bcbs/publ/wp35.htm) - March 2019

Basel Committee Working Paper with Stefan Schmitz, Katharina Steiner, Clément Martin, Oana Toader, Tomoyoshi Teramura, Mahmut Kutlukaya, Doriana Ruffino, and Irina Barakova

[GSE Guarantees, Financial Stability, and Home Equity Accumulation](https://www.newyorkfed.org/research/epr/2018/epr_2018_gse-guarantees_passmore.html)	- December 2018

Federal Reserve Bank of New York Economic Policy Review with Wayne Passmore

:::

::::